#!/bin/sh -eux

${CC} --version
SCAN=scan-build${CC#clang}
FAKEROOT="$(mktemp -d)"

# Check exports.
(cd src && ./diff_exports.sh)

# Build and install OpenSSL HEAD.
git clone --depth=1 https://github.com/openssl/openssl
cd openssl
./Configure linux-x86_64-clang --prefix="${FAKEROOT}" --openssldir="${FAKEROOT}/openssl" --libdir=lib
make install_sw
cd ..

# Build, analyze, and install libfido2.
for T in Debug Release; do
	mkdir build-$T
	export PKG_CONFIG_PATH="${FAKEROOT}/lib/pkgconfig"
	(cd build-$T && ${SCAN} --use-cc="${CC}" cmake -DCMAKE_BUILD_TYPE=$T ..)
	${SCAN} --use-cc="${CC}" --status-bugs make -C build-$T 2>&1 | tee /tmp/$T.txt
	sudo make -C build-$T install
done

# Print warning statistics.
for T in Debug Release; do
	awk '/warning:/ { print $NF }' /tmp/$T.txt | sort | uniq -c | sort -rn
done
